module.exports = {
    USER_ID: "user_id",
    USER_NAME: "username",
    DATE_OF_BIRTH: "date_of_birth",
    ADDRESS: "address",
    PHONE_NO: "phone_no",
    MAIL_ID: "mail_id",
    PROFILE_PICTURE_ID: "profile_picture_id",
    AVATAR_ID: "avatar_id",
    ABOUT: "about",
    COLLEGE_NAME: "college_name",
    STUDENT_NO: "student_no",
    BATCH_FROM: "batch_from",
    BATCH_TO: "batch_to",
    STREAM: "stream",
    SECTION: "section",
    EXPERIENCE: "experience",
    EDUCATION: "education",
    SKILLS: "skills",
    ACHIEVEMENTS: "achievements",
    CONNECTION_COUNT: "connection_count",
    VIEWERS_COUNT: "viewers_count",
};
